name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create mod folder
        run: |
          mkdir Alef-Null
          cp -r content sprites mod.hjson Alef-Null/
      
      - name: Archive mod
        run: zip -r Alef-Null.zip Alef-Null
      
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: Alef-Null.zip